
services:
  backend:
    build:
      context: ./api/api
    ports:
      - "8080:8080"
    env_file:
      - ./api/api/.env  
    networks:
      - app-network

  frontend:
    build:
      context: ./app/platform
    ports:
      - "3000:3000"
    env_file:
      - ./app/platform/.env  
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    build:
      context: .  # root
      dockerfile: ./nginx/Dockerfile  # dockerfile path
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
