# Generated by Django 5.1.5 on 2025-02-03 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('trialing', 'Trialing')], max_length=20)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.DateField()),
                ('email_pin', models.IntegerField(blank=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('password_valid', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('billing_name', models.CharField(default='', max_length=100)),
                ('billing_street_number', models.CharField(default='', max_length=100)),
                ('billing_city', models.CharField(default='', max_length=100)),
                ('billing_ZIP', models.CharField(default='', max_length=10)),
                ('billing_country', models.CharField(default='', max_length=100)),
                ('stripe_customer_id', models.CharField(max_length=50, unique=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_viewed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_prev_viewed', to='products.product')),
                ('saved', models.ManyToManyField(blank=True, to='products.product')),
                ('stripe_subscription', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.subscription')),
            ],
        ),
    ]
