# Generated by Django 5.1.5 on 2025-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('user', '0002_alter_user_email_pin_alter_user_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
