# Generated by Django 5.1.5 on 2025-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
